# Generated by Django 5.0.4 on 2024-11-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgresoHabito",
            fields=[
                ("id_progreso", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "id_habito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso del Hábito",
                "verbose_name_plural": "Progresos de los Hábitos",
                "unique_together": {("id_habito", "fecha")},
            },
        ),
    ]
