# Generated by Django 5.0.4 on 2024-11-03 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_habito", models.CharField(max_length=100)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("Diario", "Diario"),
                            ("Semanal", "Semanal"),
                            ("Mensual", "Mensual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                (
                    "objetivo",
                    models.PositiveIntegerField(
                        help_text="Repeticiones necesarias para completar el hábito."
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
